version: "3.8"
services:
  postgres:
    image: postgres:11.8
    volumes:
      - sample-postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: sample-dev-db
      POSTGRES_USER: sample-user
      POSTGRES_PASSWORD: ""
volumes:
  sample-postgresdata:
    external: false
